apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenkicloud-cache-server
  labels:
    app: tenkicloud-cache-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenkicloud-cache-server
  template:
    metadata:
      labels:
        app: tenkicloud-cache-server
    spec:
      containers:
      - name: tenkicloud-cache-server
        image: ghcr.io/aki-luxor/cache:130d21ce340a48bb08b3e934af934eb99b590b28
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"