apiVersion: v1
kind: Service
metadata:
  name: tenkicloud-cache-server
  labels:
    app: tenkicloud-cache-server
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: tenkicloud-cache-server